---
title: "Course announcement"
toc: false
date: 2023-08-01
description: "Announcement in the university's course management system"
---

**Empirisch-psychologisches Praktikum: "Theorieentwicklung / Formale Modelle in der Psychologie"**

Als eine Reaktion auf die Replikationskrise wurde der Ruf nach besseren Theorien laut, mit dem Ziel, verbale und konzeptionelle Theorien in formale, mathematische Modelle zu übersetzen. Im Empirisch-psychologischen Praktikum "Formale Modelle in der Psychologie" tauchen die Studierenden genau in diese Welt der exakten Definitionen und der quantitativen Darstellung von psychologischen Theorien ein. Dabei geht es nicht um die quantitative Auswertung von Daten mit Hilfe statistischer Modelle, sondern um Theorien und datengenerierende Modelle, die so präzise sind, dass man konkrete Daten vorhersagen kann.
Diese Modelle dienen mehreren Zwecken: Sie ermöglichen eine rigorose Prüfung von Hypothesen, bieten klarere Vorhersagen und bilden einen Rahmen, um scheinbar disparate Ergebnisse zu vereinheitlichen. Außerdem schärfen sie den Blick auf "Leerstellen" in den meist hoffnungslos unterspezifizierten Theorien in der Psychologie.

In diesem Kurs werden die Studierenden in die grundlegenden Prinzipien der formalen Modellierung eingeführt (z.B. mathematische oder agentenbasierte Modelle) und mit den Werkzeugen ausgestattet, die sie benötigen, um vorhandene verbale Theorien zu formalisieren und daraus komputationale Modelle abzuleiten. Entsprechend werden wir uns viel mit der Implementierung in R befassen. Im Gegensatz zu "klassischen" Empras werden hier keine empirischen Daten erhoben.

Wir werden versuchen, kollaborativ verbale psychologische Theorien soweit zu formalisieren, dass man sie in ein datengenerierendes Modell übersetzen und implementieren kann, und dieses dann auch testen kann. Wir üben den Prozess gemeinsam am Beispiel des bekannten "Bystander Effects" aus der Sozialpsychologie. Im zweiten Teil wenden Sie die Methode dann in Gruppenarbeit auf eine Theorie Ihrer Wahl an.

Wir werden Aspekte der Qualitätssicherung bei dieser eher ungewöhnlichen Forschungsrichtung diskutieren und anwenden (Reproduzierbarkeit, Versionskontrolle / versionierte Theorien, Sensitivitätsanalysen, Codedokumentation, unit/functional testing).

Das Empra stellt etwas höhere Anforderungen an mathematisches und formales Denken, sowie ihre Programmierfähigkeit. Als Minimum werden die R-Kenntnisse vorausgesetzt, die im Rahmen der Seminare zu Statistik 1 und 2 gelehrt wurden, sowie die Bereitschaft, sich auch selbständig (anhand von bereitgestelltem Material) in Themen der Programmierung einzuarbeiten.

Die benotete Prüfungsleistung ist ausschließlich der abgegebene Forschungsbericht. Das Abgabedatum wird ca. Mitte März sein.



Literatur:
================

Borsboom, D., van der Maas, H. L. J., Dalege, J., Kievit, R. A., & Haig, B. D. (2021). Theory Construction Methodology: A Practical Framework for Building Theories in Psychology. Perspectives on Psychological Science, 16(4), 756–766. https://doi.org/10.1177/1745691620969647

Lange, J., Freyer, N., Musfeld, P., Schönbrodt, F., & Leising, D. (2025). A Checklist for Incentivizing and Facilitating Good Theory Building. Zeitschrift Für Psychologie, 233(4), 279–283. https://doi.org/10.1027/2151-2604/a000604

Leising, D., Grenke, O., & Cramer, M. (2023). Visual Argument Structure Tool (VAST) Version 1.0. Meta-Psychology, 7. https://doi.org/10.15626/MP.2021.2911

Van Dongen, N., Van Bork, R., Finnemann, A., Haslbeck, J. M. B., Van Der Maas, H. L. J., Robinaugh, D. J., De Ron, J., Sprenger, J., & Borsboom, D. (2024). Productive explanation: A framework for evaluating explanations in psychological science. Psychological Review. https://doi.org/10.1037/rev0000479

Van Lissa, C. J., Peikert, A., Ernst, M. S., Van Dongen, N. N. N., Schönbrodt, F. D., & Brandmaier, A. M. (2026). To Be FAIR: Theory Specification Needs an Update. Perspectives on Psychological Science, 21(2), 173–191. https://doi.org/10.1177/17456916251401850
