---
title: "Formal modeling in psychology"
subtitle: "Buridan's Ass"
author:
  - name: Felix Schönbrodt
    orcid: 0000-0002-8282-3910
    email: felix.schoenbrodt@psy.lmu.de
    affiliations: Ludwig-Maximilians-Universität München
date: today
date-format: iso
footer: "Formal modeling in psychology - Empirisches Praktikum, Ludwig-Maximilians-Universität München"
format: 
  clean-revealjs: 
    output-ext: slide.html
    transition: slide
    background-transition: fade
    touch: true
    embed-resources: true
  html: default
revealjs-plugins:
  - attribution 
---

# A theory crisis in psychology? {background-color="#40666e"}

## The relation of data and phenomena

::: {.r-stretch}
```{mermaid}
%%| fig-width: 14
%%{ init: { 'flowchart': { 'curve': 'natural' } } }%%
flowchart LR
  T(Theory)
  P(Phenomena)
  D(Data)
  
  T -- "Explanation" --> P
  P -- "Abduction" --> T
  P -- "Prediction" --> D
  D -- "Generalization" --> P
```
:::

::: footer
See Borsboom et al. (2021). Theory Construction Methodology: A Practical Framework for Building Theories in Psychology. Perspectives on Psychological Science, 16(4), 756–766. [https://doi.org/10.1177/1745691620969647](https://doi.org/10.1177/1745691620969647)
:::


## The relation of data and phenomena
```{mermaid}
%%| fig-width: 6
%%{ init: { 'flowchart': { 'curve': 'natural' } } }%%
flowchart LR
  P(Phenomena)
  D(Data)
  
  P -- "Prediction" --> D
  D -- "Generalization" --> P
```

**Phenomena**: Stable and general features of the world in need of explanation. Can be understood as robust generalizations of patterns in empirical data. They are the explanatory targets for scientific theories. In psychology often called "effects" or "findings".

**Data**: Relatively direct observations. Refer to *particular* empirical patterns in concrete data sets rather than empirical generalizations (which would be phenomenona).

::: footer
See Borsboom et al. (2021). Theory Construction Methodology: A Practical Framework for Building Theories in Psychology. Perspectives on Psychological Science, 16(4), 756–766. [https://doi.org/10.1177/1745691620969647](https://doi.org/10.1177/1745691620969647)
:::




## The relation of data and phenomena
### Generalization
```{mermaid}
%%| fig-width: 6
%%{ init: { 'flowchart': { 'curve': 'natural' } } }%%
flowchart LR
  P(Phenomena)
  D(Data)
  
  P -- "Prediction" --> D
  D -- "Generalization" --> P
  
  linkStyle 1 stroke-width:2px,stroke:red,color:red;
```

::: {.r-fit-text}
Data provide evidence for the existence of empirical phenomena: You <span style="color:red;">generalize</span> from one or more data sets with strong evidence to a general phenomenon.

Generalize to *what*? UTOS framework:

- [U]{.bg style='--col: #fff100'}nits (i.e., sample characteristics): To which other types of tested units does it generalize?
- [T]{.bg style='--col: #fff100'}reatments: Does it generalize to other operationalizations of the independent variable/treatment?
- [O]{.bg style='--col: #fff100'}utcomes: Does it generalize to other operationalizations of the dependent variable/outcome?
- [S]{.bg style='--col: #fff100'}ettings: Does it generalize to other settings, e.g. lab vs. field, other countries?

To claim a (robust) phenomenon, you ideally need:

- Independent replications of specific operationalizations (U, maybe S)
- Conceptual replications with different operationalizations (UTOS).
:::

::: footer
UTOS framework from Cronbach & Shapiro (1982); for an update to "M-STOUT", including *mechanims* and *time*, see Findley et al. (2021). External Validity. Annual Review of Political Science, 24(1), 365–393. [https://doi.org/10.1146/annurev-polisci-041719-102556](https://doi.org/10.1146/annurev-polisci-041719-102556)

:::

## The relation of data and phenomena 3
```{mermaid}
%%| fig-width: 6
%%{ init: { 'flowchart': { 'curve': 'natural' } } }%%
flowchart LR
  P(Phenomena)
  D(Data)
  
  P -- "Prediction" --> D
  D -- "Generalization" --> P
  
  linkStyle 1 stroke-width:2px,stroke:red,color:red;
```

Probably most of psychology is about *establishing phenomena* (disguised as "theories").

Techniques used to detect data patterns:

- Factor analysis
- Principal components analysis
- Regression
- ANOVA
- ...

::: footer
See [presentation](https://video.uu.nl/videos/helmholtz-lecture-2023-02-10-prof-denny-borsboom/#timeline) of Denny Borsboom
:::


## The relation of data and phenomena
### Prediction
```{mermaid}
%%| fig-width: 6
%%{ init: { 'flowchart': { 'curve': 'natural' } } }%%
flowchart LR
  P(Phenomena)
  D(Data)
  
  P -- "Prediction" --> D
  D -- "Generalization" --> P
  
  linkStyle 0 stroke-width:2px,stroke:red,color:red;
```

Phenomena (once their existence has been established) [predict]{style="color:red"} similar data patterns in new data sets of the *same* operationalization (as in "direct replication") and ideally also for *new* operationalizations (as in "conceptual replication", changing more UTOS dimensions).

## Interlude: The risky shift phenomenon 1

::: {.r-fit-text}
**The risky shift phenomenon**: A group's decisions are riskier than the average of the individual decisions of members before the group met (i.e., the group discussion made individuals riskier).

::: {.incremental}
- Area of very active research in social psychology in the 1960s.
- "It could be easily replicated. Most of the replication studies [...] employed the CDQ [Choice Dilemma Questionnaire] as their stimulus set, and they generally had no trouble obtaining the basic risky shift result."
- **Today we know that there is no risky shift.** "It is now clear that the items contained in the original CDQ are in no sense a representative sample of the universe of all possible items. Instruments similar to the CDQ could readily be constructed whose scores would display risky shifts, cautious ones, or none at all" (Cartwright, 1971, p. 368).
- In the early risky shift literature, theoretical progress was unnecessarily impeded by multiple generations of replication studies (*k* ⋍ 200), nearly all relying on the same CQD questionnaire.
:::
:::

::: footer
See Westfall et al. (2015). Replicating Studies in Which Samples of Participants Respond to Samples of Stimuli. Perspectives on Psychological Science, 10(3), 390–399. https://doi.org/10.1177/1745691614564879
:::

## Interlude: The risky shift phenomenon 2

**{{< fa people-group size=2x >}} Questions for discussion (10 min.):**

- Analyse the situation in the UTOS dimensions (units, treatments, outcomes, settings): To which dimensions did the successful replications (not) refer to?
- Is the "risky shift" finding - as demonstrated in the early publications - a *phenomenon*?

. . . 

*My take*: It *is* a phenomenon (though a weak one), as it generalizes to new units (i.e., data sets) of the same operationalization. But the generalizability was much weaker than initially expected. It is a phenomenon of this specific stimulus set (*treatment operationalization*) and suggests certain types of research questions (e.g., "What is so specific to this stimulus set?").



## Replication crisis
### Focus on phenomena

```{mermaid}
%%{ init: { 'flowchart': { 'curve': 'natural' } } }%%
flowchart LR
  P(Phenomena)
  D(Data)
  
  P -- "Prediction" --> D
  D -- "Generalization" --> P
```

The concerns of the replication crisis typically referred to the relation between *data* and *phenomena*:

- Does an empirical pattern even *exist*? (Or is it a false positive?)
- If we found a reproducible pattern with a specific operationalization: Is it *generalizable* (to other measures, other cultural contexts, other samples)?
- Do we even have a phenomenon in a particular research line? And how strongly should I belief in the existence of a phenomenon, given the empirical evidence?

## Replication crisis
### Focus on phenomena

```{mermaid}
%%| fig-width: 6
%%{ init: { 'flowchart': { 'curve': 'natural' } } }%%
flowchart LR
  T(Theory)
  P(?? Phenomena ??)
  D(Data)
  
  T -- "Explanation" --> P
  P -- "Abduction" --> T
  P ---> D
  D -. "?? Generalization ??" .-> P
  
  linkStyle 2 stroke-width:0px,stroke:grey,color:grey;
  linkStyle 3 stroke-width:2px,stroke:red,color:red;
```

Doubts about phenomena propagate to theories: If there is no phenomenon to explain, any explanatory theory gets obsolete.

# From replication crisis to theory crisis

## From replication crisis to theory crisis 1

"We argue that a further cause of poor replicability is the often weak logical link between theories and their empirical tests."

::: footer
See Oberauer, K., & Lewandowsky, S. (2019). Addressing the theory crisis in psychology. Psychonomic Bulletin & Review, 26(5), 1596–1618. https://doi.org/10.3758/s13423-019-01645-2
:::

## From replication crisis to theory crisis 2

Obstacles to building useful theories in psychology:

- relative **lack of robust phenomena** that impose constraints on possible theories
- **problems of validity** of psychological constructs
- **obstacles to discovering causal relationships** between psychological variables

::: {.attribution}
Slide by [Karolin Salmen](https://www.psycharchives.org/en/item/cde1ef17-611c-42d0-8835-95592cab521a), CC-BY
:::

::: footer
See Eronen & Bringmann (2021)
:::



## From replication crisis to theory crisis 3

::: {.r-fit-text}
> Wenn die Psychologie das Fehlen eines theoretischen Fundaments beklagt, so greift diese Diagnose zu kurz: Woran es ihr eigentlich mangelt, ist ein **Nährboden**, auf dem ein solches Fundament überhaupt entstehen könnte. Ihr fehlt das große **heuristische Narrativ**. Die Physik hat ein solches Narrativ; es ist der Glaube an die Sphärenmusik einer kosmischen Harmonie, erkennbar an dem Vertrauen, mit dem man erwartet, auf Symmetrien, Erhaltungssätze und überhaupt auf einfache Zusammenhänge zu stoßen. Die Psychologen haben sich dieses Narrativ ausgeborgt; aber bei ihnen funktioniert es nicht.

> Auch für sie aber läge ein solcher Kompass bereit, und die Systemtheorie könnte sie lehren, ihn zu nutzen. Den Technikern ist er seit je vertraut, und ebenso ordnet und lenkt er das Denken der Biologen [...]. Dieses heuristische Narrativ - wir werden es in diesem Buch unter dem Stichwort des demiurgischen Prinzips kennenlernen - **ist die Vision des kosmischen Ingenieurs, des Weltbaumeisters, der den Organismus unter der Leitidee nicht der *Harmonie*, sondern der *Funktionalität*, des "Wozu" konstruiert hat**.

:::

::: footer
See Bischof (2021), "Struktur und Bedeutung"
:::



<!-- Footer insert below -->
```{r child="../../common/lastslide.qmd"}
```
